/**
 * RFC 4180 CSV, parsed and generated by hand.
 *
 * Hand-rolled rather than taken as a dependency (phase 15 §D8): this sits on the
 * path where uploaded bytes are first interpreted, the grammar is small enough
 * to test exhaustively, and `AGENTS.md` requires justifying a new production
 * dependency. The whole grammar is the state machine in `parseCsv` — quoted
 * fields, `""` escapes, embedded commas and newlines, CRLF or LF, and a BOM.
 *
 * Limits are arguments rather than constants because the two callers want
 * different ones: an import bounds a file it is about to hold a transaction
 * open for, and a generator bounds nothing.
 */

export type CsvErrorCode =
  | 'empty_file'
  | 'header_only'
  | 'unterminated_quote'
  | 'row_too_wide'
  | 'cell_too_long'
  | 'too_many_rows'
  | 'duplicate_header'
  | 'blank_header';

export class CsvError extends Error {
  constructor(
    readonly code: CsvErrorCode,
    message: string,
    readonly details: Record<string, unknown> = {},
  ) {
    super(message);
    this.name = 'CsvError';
  }
}

export function isCsvError(error: unknown): error is CsvError {
  return error instanceof CsvError;
}

export interface CsvRow {
  /**
   * The record's position counting the header as 1, so the first data row is 2
   * — what a spreadsheet shows for a file with no embedded newlines. A quoted
   * cell containing a newline makes this diverge from the physical line number;
   * the record number is the useful one, because it is what the mapping and the
   * per-row outcomes are keyed on.
   */
  rowNumber: number;
  cells: readonly string[];
}

export interface CsvTable {
  header: readonly string[];
  rows: readonly CsvRow[];
}

export interface CsvParseOptions {
  /** Data rows, excluding the header. Exceeding it is an error, not a truncation. */
  maxRows?: number;
  maxCellLength?: number;
  maxColumns?: number;
}

const defaults = { maxRows: 5000, maxCellLength: 10_000, maxColumns: 512 } as const;

/**
 * Split into records without interpreting them.
 *
 * A record that is a single empty cell is a blank line, and is dropped: files
 * exported by spreadsheet software routinely end with one, and treating it as a
 * row would report a spurious rejection on almost every real upload.
 */
function scan(text: string, limits: Required<CsvParseOptions>): string[][] {
  const source = text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
  const records: string[][] = [];
  let cells: string[] = [];
  let cell = '';
  let quoted = false;
  let index = 0;

  const endCell = () => {
    if (cell.length > limits.maxCellLength) {
      throw new CsvError('cell_too_long', 'a cell exceeds the maximum length', {
        rowNumber: records.length + 1,
        column: cells.length + 1,
        maxCellLength: limits.maxCellLength,
      });
    }
    cells.push(cell);
    cell = '';
    if (cells.length > limits.maxColumns) {
      throw new CsvError('row_too_wide', 'a row has more columns than allowed', {
        rowNumber: records.length + 1,
        maxColumns: limits.maxColumns,
      });
    }
  };

  const endRecord = () => {
    endCell();
    // A single empty cell is a blank line, not a row of one empty value.
    if (!(cells.length === 1 && cells[0] === '')) records.push(cells);
    cells = [];
    // +1 for the header, which is records[0].
    if (records.length > limits.maxRows + 1) {
      throw new CsvError('too_many_rows', 'the file has more rows than allowed', {
        maxRows: limits.maxRows,
      });
    }
  };

  while (index < source.length) {
    const char = source[index]!;
    if (quoted) {
      if (char !== '"') {
        cell += char;
        index += 1;
        continue;
      }
      // A doubled quote is one literal quote; a lone one closes the field.
      if (source[index + 1] === '"') {
        cell += '"';
        index += 2;
        continue;
      }
      quoted = false;
      index += 1;
      continue;
    }
    if (char === '"' && cell === '') {
      quoted = true;
      index += 1;
      continue;
    }
    if (char === ',') {
      endCell();
      index += 1;
      continue;
    }
    if (char === '\r' || char === '\n') {
      endRecord();
      index += char === '\r' && source[index + 1] === '\n' ? 2 : 1;
      continue;
    }
    cell += char;
    index += 1;
  }

  if (quoted) {
    throw new CsvError('unterminated_quote', 'a quoted field is never closed', {
      rowNumber: records.length + 1,
    });
  }
  // Trailing content with no final newline is still a record.
  if (cell !== '' || cells.length > 0) endRecord();
  return records;
}

/**
 * Parse a whole file into a header and its data rows.
 *
 * Ragged rows are **not** an error here. A row shorter than the header is padded
 * and a longer one keeps its extra cells, because the import reads cells by the
 * header position it mapped and a single malformed row should reject that row
 * rather than the file. `raggedRowNumbers` reports them so the caller can say so.
 */
export function parseCsv(
  text: string,
  options: CsvParseOptions = {},
): CsvTable & { raggedRowNumbers: readonly number[] } {
  const limits = { ...defaults, ...options };
  const records = scan(text, limits);
  if (records.length === 0) {
    throw new CsvError('empty_file', 'the file contains no rows');
  }
  const header = records[0]!.map((value) => value.trim());
  if (header.some((name) => name === '')) {
    throw new CsvError('blank_header', 'a column in the header row has no name', {
      column: header.indexOf('') + 1,
    });
  }
  const seen = new Set<string>();
  for (const name of header) {
    const key = name.toLowerCase();
    if (seen.has(key)) {
      throw new CsvError('duplicate_header', 'two columns share a name', { name });
    }
    seen.add(key);
  }
  if (records.length === 1) {
    throw new CsvError('header_only', 'the file has a header row but no data rows');
  }

  const ragged: number[] = [];
  const rows: CsvRow[] = records.slice(1).map((cells, index) => {
    const rowNumber = index + 2;
    if (cells.length !== header.length) ragged.push(rowNumber);
    const padded =
      cells.length >= header.length
        ? cells
        : [...cells, ...Array.from({ length: header.length - cells.length }, () => '')];
    return { rowNumber, cells: padded };
  });
  return { header, rows, raggedRowNumbers: ragged };
}

/** Sample values for the mapping UI: the first `count` non-blank values in a column. */
export function columnSamples(
  table: CsvTable,
  columnIndex: number,
  count: number,
): readonly string[] {
  const samples: string[] = [];
  for (const row of table.rows) {
    const value = row.cells[columnIndex]?.trim() ?? '';
    if (value !== '' && !samples.includes(value)) samples.push(value);
    if (samples.length === count) break;
  }
  return samples;
}

/** How many of a column's rows carry a value, 0–1. Drives the mapping UI's meter. */
export function columnFillRate(table: CsvTable, columnIndex: number): number {
  if (table.rows.length === 0) return 0;
  let filled = 0;
  for (const row of table.rows) {
    if ((row.cells[columnIndex]?.trim() ?? '') !== '') filled += 1;
  }
  return filled / table.rows.length;
}

const needsQuoting = /[",\r\n]/;

/** One CSV field. `null`/`undefined` become an empty field, not the text "null". */
export function toCsvCell(value: string | number | boolean | null | undefined): string {
  if (value === null || value === undefined) return '';
  const text = typeof value === 'string' ? value : String(value);
  return needsQuoting.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

export function toCsvRow(cells: readonly (string | number | boolean | null | undefined)[]): string {
  return cells.map(toCsvCell).join(',');
}

/**
 * A whole document. CRLF because RFC 4180 says so and because it is what
 * spreadsheet software on every platform reads without a prompt.
 */
export function toCsv(
  header: readonly string[],
  rows: readonly (readonly (string | number | boolean | null | undefined)[])[],
): string {
  return [toCsvRow(header), ...rows.map(toCsvRow)].join('\r\n') + '\r\n';
}
