environment = "staging"
aws_region  = "ap-south-1"

# App Runner's generated hostname is unknown until the service exists, so the
# first apply uses a placeholder, then `terraform output service_url` gives the
# real one and a second apply sets it. Once a custom domain is attached this
# becomes that domain and stops changing.
public_base_url = "https://placeholder.invalid"

# Must be a sender on a domain verified with the email provider. Password resets
# and marketing campaigns should not share a sending subdomain — see ADR-0018.
email_from = "Falcon CRM <no-reply@notify.wellsuresolutions.com>"
campaign_email_from = "Falcon Campaigns <news@mail.wellsuresolutions.com>"

common_tags = {
  Owner = "platform"
}

# No secret belongs in this file. The database password is generated by
# Terraform and published to Secrets Manager; the email API key is entered once
# by hand against the secret name in `terraform output email_api_key_secret_name`.
